Код ревью - 1
HrynkoKi/HTML-CSS pull request #1
Opened 2023-08-09 08:25 UTC by HrynkoKi

2023-08-11 05:34 UTC, Grinv requested changes

2023-08-11 05:34 UTC, Grinv commented on 1-Blog/index.html
> +      <input type="text" placeholder="Поиск" name="search">
Есть и `type="search"` :)

2023-08-11 05:34 UTC, Grinv commented on 2-Form/index.html
> +          <input required type="text" placeholder="Моя компания" name="company">
Очень хорошей привычкой является подставлять autocomplete. Там огромный набор вариантов, вплоть до автоподставления данны] кредитной карты. Пусть браузер делает работу за юзера, юзеру это будет приятно)
Cписок можно поизучать тут: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2023-08-11 05:34 UTC, Grinv commented on 2-Form/index.html
> +          <input required type="text" placeholder="E-mail" name="email">
`type="email"`

Мне, как пользователю, самому бывает грустно, когда не думают о мобилках, а на мобилках клавиатура отличается в зависимости от type. Пример:

![image](https://github.com/HrynkoKi/HTML-CSS/assets/4070730/11cd20a9-6a3b-44c6-8822-628fa12c3129)

2023-08-11 05:34 UTC, Grinv commented on 2-Form/index.html
> +        <label>
А зачем тут label? Внутри же нет никакого текста, связанного с input

2023-08-11 05:34 UTC, Grinv commented on 2-Form/index.html
> +
Нууу. Можно поспорить конечно)
Но я бы не стал включать заголовок h1 и "Уже есть аккаунт?" в форму. Это конечно никак не повлияет на вёрстку, просто по смыслу не очень корректно)

2023-08-11 05:34 UTC, Grinv commented on 1-Blog/index.html
> +          <a href="#">В Мой блог</a>
А почему эта ссылка отдельно, а не в списке с другими?)

Даже если хочется поставить отдельно, можно избавиться от обёртки из `div`, она тут не нужна

2023-08-11 09:29 UTC, HrynkoKi commented on 1-Blog/index.html
> +          <a href="#">В Мой блог</a>
Думал по макету, что это логотип)

2023-08-14 06:40 UTC, Grinv approved these changes

2023-08-14 06:40 UTC, merged