Код ревью - 2
HrynkoKi/HTML-CSS pull request #2
Opened 2023-08-10 11:16 UTC by HrynkoKi

2023-08-11 06:43 UTC, Grinv requested changes

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/css/index.css
> +  font-family: 'Roboto', sans-serif;
Roboto прописали, а кто сам шрифт подключать будет?)

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/css/index.css
> +img {
Слишком специфичное свойство, чтоб применять ко всем img.
Добавь пожалуйста класс для картинки и используй его

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +      <nav class="header__nav nav">
Зачем второй класс `nav`?
Да и в `header__nav` смысла не вижу, оба не используются

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +        <div class="nav__logo logo">
Зачем второй класс logo? И первый не используется

И кажется, это совсем не лого)

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +      <input type="text" placeholder="Поиск" name="search" class="header__field">
Давай применим более осмысленный класс, например `header__search`

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +        <h1 class="profile__main-title">Теория цвета - Как цвет влияет на поведение потребителей</h1>
Кажется, других заголовков тут нет, кроме h2, но там больше подходит `profile_author`
Поэтому тут можно просто `profile__title`

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +      <span class="footer__rights">Все права защищены (c) 2024</span>
Лучше не rights, а copyright

2023-08-11 06:43 UTC, Grinv commented on 2-Form/css/index.css
> +  font-family: "Open Sans", sans-serif;
Тоже самое с шрифтом. Обозначил, но тогда надо и подключить)

2023-08-11 06:43 UTC, Grinv commented on 2-Form/css/index.css
> +  color: #666;
Если это основной цвет твоей страницы, то я бы его прописал в body, тогда отсюда и из `p` можно будет убрать

2023-08-11 06:43 UTC, Grinv commented on 2-Form/css/index.css
> +}
Ни одного класса. Опасненько.
А если появится кнопка с другой вёрсткой? А потом ещё и с третьим типом?)

2023-08-11 06:43 UTC, Grinv commented on 1-Blog/index.html
> +          ><a href="#" class="nav__link">Backend</a>
Так у тебя тут ни один из классов с nav не используется. Ни `nav__list`, ни `nav__item`, ни `nav__link`
Не надо оставлять мусор)

2023-08-11 10:04 UTC, HrynkoKi commented on 1-Blog/index.html
> +      <nav class="header__nav nav">
По BEM миксин двух классов. Это заготовка на потом :)

2023-08-11 10:09 UTC, HrynkoKi commented on 1-Blog/index.html
> +          ><a href="#" class="nav__link">Backend</a>
Опять же, это заготовка на потом. Могу конечно убрать, но потом нужно будет добавить обратно)

2023-08-14 06:44 UTC, Grinv commented on 1-Blog/index.html
> +          ><a href="#" class="nav__link">Backend</a>
Опять же, потом может не понадобиться или забудешь и будет так висеть)

2023-08-14 06:44 UTC, Grinv approved these changes

2023-08-14 08:02 UTC, merged